# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

target 'ICONKit-example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  # Pods for ICONKit-example
  pod 'ICONKit', :path => '~/ICONKit/'

#  target 'ICONKit-exampleTests' do
#    inherit! :search_paths
#  end

end
